### ISSUE TITLE
Nonatomic Queue Operations

### ISSUE THREAD

**Issue by thygrrr** [genaray/ZeroAllocJobScheduler#33]
The following operation in RangeWorkStealingDeque is not atomic.

```cs
var b = Volatile.Read(ref _bottom);
// we're popping, so decrement the bottom in advance.
// Doing this in advance ensures that we "reserve space" in the size, so that even if someone steals,
// they can't steal past this _bottom (their size would return less than 0, and they wouldn't steal). 
// At the end of this method, if we need to adjust this (i.e. there ended up being nothing to steal, or less than amount to steal)
// we resolve this.
b--;
Volatile.Write(ref _bottom, b);
```

suggesting to replace with:

```cs
var b = Interlocked.Decrement(ref _bottom);
```

**Comment by thygrrr** [comment]
Possibly irrelevant given the way this Deque claims to work.
(not every comment is very reassuring though!:)

**Comment by genaray** [comment]
Can you explain why Volatile is not atomic and Interlocked is? (Just out of curiosity)
@LilithSilver Might also be interested in this one.

**Comment by LilithSilver** [comment]
Hi! Good question. A couple notes on this:

1. This is currently being stripped out in #29, so it will cease to be relevant soon. This is because it is exclusively used for IJobParallelFor. 
2. Interlocked is significantly slower than Volatile. As the comment claims, if the value is changed by a different thread as it's being read (i.e. someone else steals while we're trying to pop), we're able to undo that value because the CAS operation will later fail. Of note, only a single thread is able to call the pop method, while any thread can steal. And, you'll note that _bottom is only read by the steal method, not ever written. Therefore, if steal gets an out of date _bottom, no problem! It will just lose the race.
3. RangeWorkStealingDeque is a special case of the work stealing Deque found on this paper: https://tsung-wei-huang.github.io/papers/icpads20.pdf A proper implementation can be found in JobScheduler.WorkStealing.cs, if you're interested.

**Comment by LilithSilver** [comment]
> Can you explain why Volatile is not atomic and Interlocked is?

To answer your question @genaray, the issue here is that the code reads, iterates, and then writes. In between those two lines, if the method were called by a different thread, those operations might get interleaved! But only the owning thread can use TryPopBottom, the others must TrySteal.

**Comment by genaray** [comment]
> > Can you explain why Volatile is not atomic and Interlocked is?
> 
> To answer your question @genaray, the issue here is that the code reads, iterates, and then writes. In between those two lines, if the method were called by a different thread, those operations might get interleaved! But only the owning thread can use TryPopBottom, the others must TrySteal.

Thanks a lot for your explanations, comments and pr! :)
